title: Robert Godfrey | Professional Portfolio
url: "https://robertgodfrey.github.io"
baseurl: ""

# OPTIONAL CHANGES
## Specify the theme using any of the css files in css/techfolio-theme
techfolio-theme: jetbrains.css
## Specify the formatting for triple backquote code sections.
rouge-theme: base16.css

# DON'T CHANGE THE FOLLOWING (unless you know what you're doing)
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
strict_front_matter: true
mathjax: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
include:
  - .nojekyll
  - _data
plugins:
  - jekyll-gist
